### ISSUE TITLE
Why has this project been abandoned?

### ISSUE THREAD

**Issue by NebelNidas** [sidit77/EasierEnchanting#3]
Would have been nice if you at least could have given an explanation. If you really don't want to continue development, would it be ok if I fork the project and continue development myself?

**Comment by sidit77** [comment]
Sorry, for the **very** late reply. I somehow unwatched my own project. The reason I stopped updating this mod is because I'm not the most active Minecraft player and I simply lost interest. I intentionally created the [update gui](https://github.com/sidit77/EasierEnchanting/blob/master/Fabric/FabricUpdater.java) and update instructions, because I knew I would lose interest and wanted the make the barrier for updating it as low as possible. Also my curseforge account got somehow deleted so I couldn't update this mod even if I wanted. Feel free to update this mod and make your own page.

**Comment by NebelNidas** [comment]
Thanks for the response! Better late than never. Seems like fanta has picked up the project, so I can close this issue now :)
https://www.curseforge.com/minecraft/mc-mods/easier-enchanting-updatet
